language: haskell
before_install:
 - travis_retry cabal install alex
 - travis_retry cabal install happy
 - travis_retry cabal install gtk2hs-buildtools
install: 
 - cd yi
 - travis_retry cabal install -fpango --enable-tests -ftesting --only-dependencies
 - cabal install -fpango --enable-tests -ftesting
 - cd -
 - cd yi-contrib
 - cabal install
