#!/bin/bash
( 
    cd yi/ && \
        runhaskell Setup.hs configure --user && \
        runhaskell Setup.hs build && \
        runhaskell Setup.hs install --user 
) && \
( 
    cd yi-contrib/ && \
        runhaskell Setup.hs configure --user && \
        runhaskell Setup.hs build && \
        runhaskell Setup.hs install --user 
)
